title: [MYOB Web Application AccountRight Sample in ASP.NET C#]
description: [Web application developed in asp.net c# to for reporting and automatic backup purpose for company file in myob cloud.]
plugins:
  - jekyll-seo-tag